version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    platform: linux/arm64
    container_name: etcd
    mem_limit: 512m           # Limita memória do contêiner
    cpus: 0.5                 # Limita uso da CPU
    ports:
      - "2379:2379"   # API de cliente
      - "2380:2380"   # Comunicação entre nós etcd
    networks:
      - patroni_net
    command: >
      etcd
      --name node1
      --initial-advertise-peer-urls http://etcd:2380
      --listen-peer-urls http://0.0.0.0:2380
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd:2379
      --initial-cluster node1=http://etcd:2380
      --initial-cluster-token etcd-cluster
      --initial-cluster-state new
      --enable-v2=true
    volumes:
      - ./data/etcd:/etcd-data

  patroni1:
    image: stablecog/spilo:15.14-latest-arm64
    platform: linux/arm64
    mem_limit: 512m           # Limita memória do contêiner
    cpus: 0.5                 # Limita uso da CPU
    container_name: patroni1
    ports:
      - "5432:5432"   # PostgreSQL
      - "8008:8008"   # API REST Patroni
    networks:
      - patroni_net
    environment:
      - SCOPE=postgres-cluster
      - PGVERSION=15
      - DCS_ENABLE=true
      - ETCD_HOST=etcd:2379
      - PATRONI_NAME=patroni1
      - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PATRONI_RESTAPI_CONNECT_ADDRESS=patroni1:8008
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=patroni1:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/home/postgres/pgdata/data
      - PATRONI_SUPERUSER_USERNAME=postgres
      - PATRONI_SUPERUSER_PASSWORD=postgres
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD=rep-pass
    depends_on:
      - etcd

  patroni2:
    image: stablecog/spilo:15.14-latest-arm64
    platform: linux/arm64
    mem_limit: 512m           # Limita memória do contêiner
    cpus: 0.5                 # Limita uso da CPU
    container_name: patroni2
    ports:
      - "5433:5432"   # PostgreSQL
      - "8010:8008"   # API REST Patroni
    networks:
      - patroni_net
    environment:
      - SCOPE=postgres-cluster
      - PGVERSION=15
      - DCS_ENABLE=true
      - ETCD_HOST=etcd:2379
      - PATRONI_NAME=patroni2
      - PATRONI_RESTAPI_LISTEN=0.0.0.0:8008
      - PATRONI_RESTAPI_CONNECT_ADDRESS=patroni2:8008
      - PATRONI_POSTGRESQL_LISTEN=0.0.0.0:5432
      - PATRONI_POSTGRESQL_CONNECT_ADDRESS=patroni2:5432
      - PATRONI_POSTGRESQL_DATA_DIR=/home/postgres/pgdata/data
      - PATRONI_SUPERUSER_USERNAME=postgres
      - PATRONI_SUPERUSER_PASSWORD=postgres
      - PATRONI_REPLICATION_USERNAME=replicator
      - PATRONI_REPLICATION_PASSWORD=rep-pass
    depends_on:
      - etcd

  haproxy:
    image: haproxy:2.9
    mem_limit: 512m           # Limita memória do contêiner
    cpus: 0.5                 # Limita uso da CPU
    platform: linux/arm64
    container_name: haproxy
    ports:
      - "6432:5432"   # Porta externa para apps se conectarem via HAProxy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - patroni_net
    depends_on:
      - patroni1
      - patroni2

networks:
  patroni_net:
    driver: bridge
